# Generated by Django 5.1.6 on 2025-03-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_remove_produto_quantidade_alter_venda_vendedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='data_venda',
        ),
        migrations.AddField(
            model_name='venda',
            name='ano_venda',
            field=models.IntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030)], default=2025),
        ),
        migrations.AddField(
            model_name='venda',
            name='mes_venda',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=3),
        ),
        migrations.AlterField(
            model_name='venda',
            name='quantidade_vendida',
            field=models.PositiveIntegerField(),
        ),
    ]
