# Generated by Django 5.1.6 on 2025-03-02 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_alter_arquivovendedor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Vendedora', 'verbose_name_plural': 'Vendedoras'},
        ),
    ]
