# Generated by Django 5.1.6 on 2025-03-03 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='dia_venda',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
