# Generated by Django 5.1.6 on 2025-03-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_alter_venda_dia_venda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='ano_venda',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='dia_venda',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='mes_venda',
        ),
        migrations.AddField(
            model_name='venda',
            name='data_venda',
            field=models.DateField(blank=True, null=True),
        ),
    ]
