# Generated by Django 5.1.6 on 2025-03-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_remove_venda_ano_venda_remove_venda_dia_venda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_venda',
            field=models.DateField(),
        ),
    ]
