# Generated by Django 5.1.6 on 2025-03-05 09:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_alter_venda_data_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivovendedor',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
