# Generated by Django 5.1.6 on 2025-03-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0008_arquivovendedor_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='valor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='valor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='venda',
            unique_together={('produto', 'vendedor', 'data_venda')},
        ),
    ]
