# Generated by Django 5.1.6 on 2025-03-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0009_produto_quantidade_produto_valor_venda_valor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='quantidade',
        ),
        migrations.AlterField(
            model_name='venda',
            name='valor',
            field=models.FloatField(),
        ),
    ]
