# Generated by Django 5.1.6 on 2025-03-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0012_alter_produto_valor_alter_venda_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='loja',
        ),
        migrations.AddField(
            model_name='customuser',
            name='lojas',
            field=models.ManyToManyField(blank=True, to='vendas.loja'),
        ),
    ]
