# Generated by Django 5.1.6 on 2025-03-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0013_remove_customuser_loja_customuser_lojas'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAcrescimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_pecas', models.PositiveIntegerField(verbose_name='Mínimo de Peças')),
                ('max_pecas', models.PositiveIntegerField(blank=True, null=True, verbose_name='Máximo de Peças')),
                ('acrescimo', models.FloatField(verbose_name='Valor do Acréscimo')),
            ],
            options={
                'ordering': ['min_pecas'],
            },
        ),
    ]
