# Generated by Django 5.1.6 on 2025-04-10 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0014_metaacrescimo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='venda',
            unique_together={('produto', 'vendedor', 'data_venda', 'loja')},
        ),
    ]
